version: 2

models:
  - name: stg_greenery_users
    description: "Greenery user details"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
